### ISSUE TITLE
Cannot install font-literata: BUG: config.c:129: kvi should not be set while parsing a config source

### ISSUE THREAD

**Issue by homocomputeris** [Homebrew/homebrew-cask-fonts#7718]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Cannot install font-literata:
```
brew install --force font-literata
==> Cloning https://github.com/google/fonts.git
Updating /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse
BUG: config.c:129: kvi should not be set while parsing a config source
Error: Download failed on Cask 'font-literata' with message: Failure while executing; `/usr/bin/env git fetch origin` was terminated by uncaught signal ABRT. Here's the output:
BUG: config.c:129: kvi should not be set while parsing a config source
```

### Command that failed

brew install --force font-literat

### Output of command with `--verbose --debug`

```shell
brew install --verbose --debug --force font-literata
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Cloning https://github.com/google/fonts.git
/usr/bin/env git --git-dir /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse/.git status -s
Updating /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse
/usr/bin/env git config remote.origin.url https://github.com/google/fonts.git
/usr/bin/env git config remote.origin.fetch \+refs/heads/main:refs/remotes/origin/main
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git config origin.partialclonefilter blob:none
/usr/bin/env git config core.sparseCheckout true
/usr/bin/env git fetch origin
BUG: config.c:129: kvi should not be set while parsing a config source
Error: Download failed on Cask 'font-literata' with message: Failure while executing; `/usr/bin/env git fetch origin` was terminated by uncaught signal ABRT. Here's the output:
BUG: config.c:129: kvi should not be set while parsing a config source

/usr/local/Homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:26:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:161:in `command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:985:in `update_repo'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:878:in `update'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:205:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.
brew doctor  4.31s user 3.07s system 83% cpu 8.818 total

brew config
HOMEBREW_VERSION: 4.0.20-20-ge9a1cd4
ORIGIN: https://github.com/Homebrew/brew
HEAD: e9a1cd41d78c7c99ccf415be24727756cfa3ec5f
Last commit: 14 hours ago
Core tap JSON: 04 Jun 21:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

### Output of `brew tap`

```shell
brew tap
bell-sw/liberica
homebrew-ffmpeg/ffmpeg
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/services
```

**Comment by kevinm6** [comment]
> Thanks @homocomputeris and @krehel! This seems related to `git 2.41.0`. Will be looking into it some more.

Hello @razvanazamfirei, is happening the same with `font-source-code-pro`!
I’ve noticed that new **casks** with the `only_path` options in the **formula spec** don’t result installed due to probably the usage of `git sparse-checkout`.

Let me know if I can help debug it more!

**Comment by razvanazamfirei** [comment]
@homocomputeris, @kevinm6 

Thank you all for looking into this. This is an issue with `git`, but a solution was implemented and this should be resolved once you update homebrew.

**Comment by kevinm6** [comment]
@razvanazamfirei I’ve just **update Homebrew**, remove and installed again those fonts;
now they result **correctly installed** but I’m still seeing the issue with the `upgrade` of them: since I’ve set the `ENV` var `HOMEBREW_UPGRADE_GREEDY=latest` or the same passing it from command line (`brew upgrade —greedy-latest`) the output is:

```bash
brew upgrade —-greedy-latest
==> Upgrading 2 outdated packages:
font-literata latest -> latest
font-source-code-pro latest -> latest
```
---

I didn’t dive into **Homebrew code**, but I assume that for **upgrade casks and formula** it checks the **hash of last commit**; however, in the case of `git sparse-checkout` maybe it's appropriate to check the `commit hash` of the **installed cask** (i.e. specific subdir in the repo).

**Comment by razvanazamfirei** [comment]
@kevinm6, I haven't been able to reproduce that. Are you still seeing the issue after running:
```
brew cleanup --prune=all
``` 

If so could you post the output of the command with `--verbose --debug`, `brew doctor` and `brew config`.

Thank you!

**Comment by kevinm6** [comment]
@razvanazamfirei 

`brew doctor` output:
`Your system is ready to brew.`

---

`brew config` output:

```bash
HOMEBREW_VERSION: 4.0.22-4-g5097876
ORIGIN: https://github.com/Homebrew/brew
HEAD: 50978768910221d8ad8c671a9d095af16d33d824
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5dc77f1116c04c7b81d3deca1c2b58c2776d17d6
Core tap last commit: 2 days ago
Core tap branch: master
Core tap JSON: 13 Jun 09:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /Users/Kevin/.config/bat/config
HOMEBREW_BROWSER: open
HOMEBREW_CACHE: /Users/Kevin/.cache/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=/Applications", "--fontdir=/Library/Fonts"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 60
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 6
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.DYCzcC1ZSi/org.xquartz:0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: ☕️
HOMEBREW_LOGS: /Users/Kevin/.cache/homebrew/logs
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_GOOGLE_ANALYTICS: set
HOMEBREW_SSH_CONFIG_PATH: /Users/Kevin/.ssh/config
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/opt/git/bin/git
Curl: 8.1.2 => /opt/homebrew/opt/curl/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1 => /Applications/Xcode-14.3.1.app/Contents/Developer
Rosetta 2: false
```

---

`brew upgrade --greedy-latest --verbose --debug` output:
[brew_upgrade_greedy_latest.txt](https://github.com/Homebrew/homebrew-cask-fonts/files/11733537/brew-output.txt)

**Comment by razvanazamfirei** [comment]
@homocomputeris, thanks for providing this. It looks like they're upgrading properly, we're just not noticing that the cask file is the same. This can be a side-effect of `:latest`, but feel free to open an issue in the main repo or submit a PR. :)  

BTW, `HOMEBREW_UPGRADE_GREEDY` doesn't take any arguments; if set it just passes `--greedy`.
